import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ReportSegment, SegmentType } from "../../types";

interface PDFGeneratorConfig {
  reportName: string;
  projectName: string;
  simulationData: {
    solarCapacityKwp: number;
    batteryCapacityKwh: number;
    annualSavings: number;
    paybackYears: number;
    roiPercent: number;
    co2AvoidedTons: number;
    dcAcRatio: number;
  };
  projectDetails?: {
    location?: string;
    total_area_sqm?: number;
    connection_size_kva?: number;
    tariffs?: {
      name?: string;
      tariff_type?: string;
      municipalities?: { name?: string };
    };
  };
  aiNarratives?: Partial<Record<SegmentType, { narrative: string; keyHighlights: string[] }>>;
  aiNarrativeEnabled?: boolean;
  editedNarratives?: Partial<Record<SegmentType, string>>;
}

// Professional color palette
const COLORS = {
  primary: { r: 34, g: 197, b: 94 },      // Emerald green
  primaryDark: { r: 22, g: 163, b: 74 },
  secondary: { r: 15, g: 23, b: 42 },      // Slate dark
  accent: { r: 59, g: 130, b: 246 },       // Blue
  warning: { r: 245, g: 158, b: 11 },      // Amber
  danger: { r: 239, g: 68, b: 68 },        // Red
  muted: { r: 100, g: 116, b: 139 },
  background: { r: 248, g: 250, b: 252 },
  white: { r: 255, g: 255, b: 255 },
};

const SEGMENT_TITLES: Record<SegmentType, string> = {
  executive_summary: "Executive Summary",
  dcac_comparison: "DC/AC Ratio Analysis",
  energy_flow: "Energy Flow Diagram",
  monthly_yield: "Monthly Yield Analysis",
  payback_timeline: "Financial Payback",
  sensitivity_analysis: "Sensitivity Analysis",
  savings_breakdown: "Savings Breakdown",
  environmental_impact: "Environmental Impact",
  engineering_specs: "Engineering Specifications",
  ai_infographics: "AI Infographics",
  tariff_details: "Tariff Analysis",
  sizing_comparison: "Sizing Alternatives",
  custom_notes: "Notes & Annotations",
};

export async function generateProfessionalPDF(
  segments: ReportSegment[],
  config: PDFGeneratorConfig
): Promise<void> {
  const { reportName, projectName, simulationData, projectDetails, aiNarratives, aiNarrativeEnabled, editedNarratives } = config;
  const enabledSegments = segments.filter(s => s.enabled).sort((a, b) => a.order - b.order);
  
  const pdf = new jsPDF("portrait", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  
  // Helper functions
  const setColor = (color: { r: number; g: number; b: number }) => {
    pdf.setTextColor(color.r, color.g, color.b);
  };
  
  const setFill = (color: { r: number; g: number; b: number }) => {
    pdf.setFillColor(color.r, color.g, color.b);
  };

  const getNarrative = (segmentId: SegmentType): string | undefined => {
    if (!aiNarrativeEnabled) return undefined;
    const edited = editedNarratives?.[segmentId];
    if (edited !== undefined) return edited;
    return aiNarratives?.[segmentId]?.narrative;
  };

  const renderNarrativeBox = (narrative: string | undefined, yPos: number, title: string): number => {
    if (!narrative) return yPos;
    
    // Narrative container
    setFill(COLORS.background);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(80, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    // Title
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    setColor(COLORS.primaryDark);
    pdf.text(title, margin + 6, yPos + 8);
    
    // AI badge
    setFill({ r: 220, g: 252, b: 231 });
    pdf.roundedRect(pageWidth - margin - 28, yPos + 3, 24, 7, 2, 2, "F");
    pdf.setFontSize(6);
    setColor(COLORS.primaryDark);
    pdf.text("AI-Generated", pageWidth - margin - 26, yPos + 8);
    
    // Narrative text
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    setColor({ r: 60, g: 60, b: 60 });
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 16);
    
    return yPos + boxHeight + 8;
  };

  const addPageFooter = (pageNum: number, totalPages: number) => {
    setFill(COLORS.secondary);
    pdf.rect(0, pageHeight - 10, pageWidth, 10, "F");
    pdf.setFontSize(7);
    setColor(COLORS.white);
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin - 18, pageHeight - 4);
    pdf.text("Generated by SolarSim Pro", margin, pageHeight - 4);
  };

  // ========== COVER PAGE ==========
  // Header band
  setFill(COLORS.secondary);
  pdf.rect(0, 0, pageWidth, 55, "F");
  
  // Project name
  pdf.setFontSize(26);
  pdf.setFont("helvetica", "bold");
  setColor(COLORS.white);
  pdf.text(projectName, margin, 28);
  
  // Subtitle
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "normal");
  pdf.text("Solar Energy Proposal", margin, 40);
  
  // Date
  pdf.setFontSize(9);
  pdf.text(new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin - 50, 28);

  // Key metrics row
  let yPos = 70;
  const metricCardWidth = (contentWidth - 20) / 3;
  
  const metrics = [
    { label: "Solar Capacity", value: `${simulationData.solarCapacityKwp} kWp`, color: COLORS.primary },
    { label: "Battery Storage", value: `${simulationData.batteryCapacityKwh} kWh`, color: COLORS.accent },
    { label: "Annual Savings", value: `R${Math.round(simulationData.annualSavings).toLocaleString()}`, color: COLORS.warning },
  ];
  
  metrics.forEach((metric, i) => {
    const x = margin + i * (metricCardWidth + 10);
    
    // Card background
    setFill(COLORS.background);
    pdf.roundedRect(x, yPos, metricCardWidth, 35, 4, 4, "F");
    
    // Left accent bar
    setFill(metric.color);
    pdf.rect(x, yPos, 3, 35, "F");
    
    // Value
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    setColor(metric.color);
    pdf.text(metric.value, x + 10, yPos + 18);
    
    // Label
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    setColor(COLORS.muted);
    pdf.text(metric.label, x + 10, yPos + 28);
  });

  yPos += 50;

  // ROI and Payback section
  const halfWidth = (contentWidth - 10) / 2;
  
  // ROI Card
  setFill(COLORS.background);
  pdf.roundedRect(margin, yPos, halfWidth, 45, 4, 4, "F");
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  setColor(COLORS.secondary);
  pdf.text("Return on Investment", margin + 10, yPos + 12);
  
  pdf.setFontSize(32);
  setColor(COLORS.primary);
  pdf.text(`${Math.round(simulationData.roiPercent)}%`, margin + 10, yPos + 35);
  
  // Payback Card
  const paybackX = margin + halfWidth + 10;
  setFill(COLORS.background);
  pdf.roundedRect(paybackX, yPos, halfWidth, 45, 4, 4, "F");
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  setColor(COLORS.secondary);
  pdf.text("Payback Period", paybackX + 10, yPos + 12);
  
  pdf.setFontSize(32);
  setColor(COLORS.primary);
  pdf.text(`${simulationData.paybackYears.toFixed(1)} yrs`, paybackX + 10, yPos + 35);
  
  yPos += 60;

  // Table of Contents
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  setColor(COLORS.secondary);
  pdf.text("Report Contents", margin, yPos);
  yPos += 10;

  enabledSegments.forEach((segment, index) => {
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    setColor(COLORS.muted);
    
    const num = (index + 1).toString().padStart(2, "0");
    pdf.text(`${num}`, margin, yPos);
    
    setColor(COLORS.secondary);
    pdf.text(SEGMENT_TITLES[segment.type], margin + 12, yPos);
    
    setColor(COLORS.muted);
    pdf.text(`Page ${index + 2}`, pageWidth - margin - 20, yPos);
    
    yPos += 7;
  });

  const totalPages = enabledSegments.length + 1;
  addPageFooter(1, totalPages);

  // ========== CONTENT PAGES ==========
  for (let i = 0; i < enabledSegments.length; i++) {
    const segment = enabledSegments[i];
    pdf.addPage();
    yPos = 20;

    // Page header with accent bar
    setFill(COLORS.primary);
    pdf.rect(0, 0, pageWidth, 20, "F");
    
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    setColor(COLORS.white);
    pdf.text(SEGMENT_TITLES[segment.type], margin, 14);

    yPos = 32;

    // Render content based on segment type
    switch (segment.type) {
      case "executive_summary":
        yPos = renderExecutiveSummary(pdf, yPos, margin, contentWidth, simulationData, projectDetails, getNarrative("executive_summary"));
        break;
      
      case "tariff_details":
        yPos = renderTariffDetails(pdf, yPos, margin, contentWidth, pageWidth, projectDetails, getNarrative("tariff_details"));
        break;
      
      case "dcac_comparison":
        yPos = renderDcAcComparison(pdf, yPos, margin, contentWidth, pageWidth, simulationData, getNarrative("dcac_comparison"));
        break;
      
      case "payback_timeline":
        yPos = renderPaybackTimeline(pdf, yPos, margin, contentWidth, pageWidth, simulationData, getNarrative("payback_timeline"));
        break;
      
      case "environmental_impact":
        yPos = renderEnvironmentalImpact(pdf, yPos, margin, contentWidth, pageWidth, simulationData, getNarrative("environmental_impact"));
        break;
      
      case "monthly_yield":
        yPos = renderMonthlyYield(pdf, yPos, margin, contentWidth, simulationData, getNarrative("monthly_yield"));
        break;
      
      case "energy_flow":
        yPos = renderEnergyFlow(pdf, yPos, margin, contentWidth, pageWidth, simulationData, getNarrative("energy_flow"));
        break;
      
      case "sizing_comparison":
        yPos = renderSizingComparison(pdf, yPos, margin, pageWidth, simulationData, getNarrative("sizing_comparison"));
        break;
      
      case "sensitivity_analysis":
        yPos = renderSensitivityAnalysis(pdf, yPos, margin, contentWidth, pageWidth, simulationData, getNarrative("sensitivity_analysis"));
        break;
      
      case "engineering_specs":
        yPos = renderEngineeringSpecs(pdf, yPos, margin, pageWidth, simulationData, getNarrative("engineering_specs"));
        break;
      
      default:
        pdf.setFontSize(10);
        setColor(COLORS.muted);
        pdf.text("Content for this section.", margin, yPos);
    }

    addPageFooter(i + 2, totalPages);
  }

  pdf.save(`${reportName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
}

// Individual section renderers
function renderExecutiveSummary(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  projectDetails: PDFGeneratorConfig["projectDetails"],
  narrative?: string
): number {
  let yPos = startY;
  
  // AI Narrative if available
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(90, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Executive Summary", margin + 6, yPos + 10);
    
    // AI badge
    pdf.setFillColor(220, 252, 231);
    pdf.roundedRect(margin + contentWidth - 30, yPos + 4, 26, 8, 2, 2, "F");
    pdf.setFontSize(6);
    pdf.text("AI-Generated", margin + contentWidth - 28, yPos + 9);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 20);
    
    yPos += boxHeight + 10;
  }

  // Key metrics grid
  const cardW = (contentWidth - 15) / 4;
  const cardH = 35;
  
  const keyMetrics = [
    { label: "Solar Capacity", value: `${data.solarCapacityKwp}`, unit: "kWp", color: COLORS.primary },
    { label: "Battery Storage", value: `${data.batteryCapacityKwh}`, unit: "kWh", color: COLORS.accent },
    { label: "Annual Savings", value: `R${Math.round(data.annualSavings / 1000)}k`, unit: "/year", color: COLORS.warning },
    { label: "Payback Period", value: data.paybackYears.toFixed(1), unit: "years", color: COLORS.primaryDark },
  ];
  
  keyMetrics.forEach((metric, i) => {
    const x = margin + i * (cardW + 5);
    
    pdf.setFillColor(metric.color.r, metric.color.g, metric.color.b);
    pdf.roundedRect(x, yPos, cardW, cardH, 3, 3, "F");
    
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(255, 255, 255);
    pdf.text(metric.value, x + 6, yPos + 16);
    
    pdf.setFontSize(8);
    pdf.text(metric.unit, x + 6, yPos + 24);
    
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.text(metric.label, x + 6, yPos + 31);
  });

  yPos += cardH + 15;

  // Project details table
  const tableData = [];
  if (projectDetails?.location) tableData.push(["Location", projectDetails.location]);
  if (projectDetails?.total_area_sqm) tableData.push(["Building Area", `${Number(projectDetails.total_area_sqm).toLocaleString()} m²`]);
  if (projectDetails?.connection_size_kva) tableData.push(["Grid Connection", `${projectDetails.connection_size_kva} kVA`]);
  if (projectDetails?.tariffs?.name) tableData.push(["Tariff", projectDetails.tariffs.name]);
  if (data.dcAcRatio) tableData.push(["DC/AC Ratio", `${data.dcAcRatio.toFixed(2)}:1`]);
  
  if (tableData.length > 0) {
    autoTable(pdf, {
      startY: yPos,
      head: [["Parameter", "Value"]],
      body: tableData,
      theme: "striped",
      headStyles: { fillColor: [34, 197, 94], textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
    });
  }

  return (pdf as any).lastAutoTable?.finalY || yPos + 50;
}

function renderTariffDetails(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  projectDetails: PDFGeneratorConfig["projectDetails"],
  narrative?: string
): number {
  let yPos = startY;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(60, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Tariff Overview", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  // TOU Periods Section
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Time-of-Use Rate Periods (Weekday)", margin, yPos);
  yPos += 10;

  // TOU Period cards
  const periods = [
    { name: "Peak", hours: "06:00-08:00, 18:00-21:00", color: COLORS.danger, description: "Highest rates" },
    { name: "Standard", hours: "08:00-18:00, 21:00-22:00", color: COLORS.warning, description: "Mid-tier rates" },
    { name: "Off-Peak", hours: "22:00-06:00", color: COLORS.primary, description: "Lowest rates" },
  ];
  
  const periodCardW = (contentWidth - 10) / 3;
  periods.forEach((period, i) => {
    const x = margin + i * (periodCardW + 5);
    
    pdf.setFillColor(period.color.r, period.color.g, period.color.b);
    pdf.roundedRect(x, yPos, periodCardW, 40, 3, 3, "F");
    
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(255, 255, 255);
    pdf.text(period.name, x + 8, yPos + 14);
    
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text(period.hours, x + 8, yPos + 24);
    pdf.text(period.description, x + 8, yPos + 34);
  });

  yPos += 55;

  // Seasonal Calendar
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Seasonal Calendar", margin, yPos);
  yPos += 10;

  const months = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"];
  const monthW = contentWidth / 12;
  
  months.forEach((m, i) => {
    const isWinter = i >= 5 && i <= 7;
    pdf.setFillColor(isWinter ? 239 : 34, isWinter ? 68 : 197, isWinter ? 68 : 94);
    pdf.roundedRect(margin + i * monthW, yPos, monthW - 1, 20, 2, 2, "F");
    
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(255, 255, 255);
    pdf.text(m, margin + i * monthW + monthW / 2 - 3, yPos + 13);
  });

  yPos += 30;
  
  // Legend
  pdf.setFillColor(239, 68, 68);
  pdf.rect(margin, yPos, 10, 6, "F");
  pdf.setFontSize(8);
  pdf.setTextColor(60, 60, 60);
  pdf.text("High Demand Season (Winter)", margin + 14, yPos + 5);
  
  pdf.setFillColor(34, 197, 94);
  pdf.rect(margin + 80, yPos, 10, 6, "F");
  pdf.text("Low Demand Season (Summer)", margin + 94, yPos + 5);

  return yPos + 20;
}

function renderDcAcComparison(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  const ratio = data.dcAcRatio || 1.3;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(70, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("DC/AC Analysis Overview", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  // Ratio comparison header
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("DC/AC Oversizing Comparison", margin, yPos);
  yPos += 12;

  // Three comparison cards
  const calcYield = (r: number) => Math.round((1 + (r - 1) * 0.6) * 100);
  const scenarios = [
    { ratio: 1.0, label: "Conservative", yield: calcYield(1.0), color: COLORS.muted },
    { ratio: ratio, label: "Current Design", yield: calcYield(ratio), color: COLORS.primary, isCurrent: true },
    { ratio: 1.5, label: "Aggressive", yield: calcYield(1.5), color: COLORS.warning },
  ];
  
  const cardW = (contentWidth - 10) / 3;
  scenarios.forEach((scenario, i) => {
    const x = margin + i * (cardW + 5);
    
    // Card background
    if (scenario.isCurrent) {
      pdf.setFillColor(240, 253, 244);
      pdf.roundedRect(x, yPos, cardW, 55, 4, 4, "F");
      pdf.setDrawColor(34, 197, 94);
      pdf.setLineWidth(1.5);
      pdf.roundedRect(x, yPos, cardW, 55, 4, 4, "S");
    } else {
      pdf.setFillColor(250, 250, 250);
      pdf.roundedRect(x, yPos, cardW, 55, 4, 4, "F");
    }
    
    // Ratio
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(scenario.color.r, scenario.color.g, scenario.color.b);
    pdf.text(`${scenario.ratio.toFixed(2)}:1`, x + cardW / 2 - 12, yPos + 16);
    
    // Label
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100, 100, 100);
    pdf.text(scenario.label, x + 6, yPos + 28);
    
    // Yield
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(scenario.color.r, scenario.color.g, scenario.color.b);
    pdf.text(`${scenario.yield}%`, x + cardW / 2 - 12, yPos + 48);
    
    pdf.setFontSize(8);
    pdf.setTextColor(100, 100, 100);
    pdf.text("yield", x + cardW / 2 + 10, yPos + 48);
  });

  yPos += 70;

  // Energy gain highlight
  const gainPct = calcYield(ratio) - calcYield(1.0);
  pdf.setFillColor(220, 252, 231);
  pdf.roundedRect(margin, yPos, contentWidth, 25, 4, 4, "F");
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(22, 101, 52);
  pdf.text(`Energy Gain vs 1:1 Baseline: +${gainPct}%`, margin + 10, yPos + 10);
  
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text("Additional energy captured during morning and evening hours", margin + 10, yPos + 20);

  return yPos + 40;
}

function renderPaybackTimeline(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  const payback = data.paybackYears;
  const annualSave = data.annualSavings;
  const systemCost = data.solarCapacityKwp * 12000 + data.batteryCapacityKwh * 6000;
  const total25yr = annualSave * 25 - systemCost;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(70, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Financial Analysis", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  // Summary metrics row
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Investment Summary", margin, yPos);
  yPos += 12;

  const cardW = (contentWidth - 10) / 3;
  const finMetrics = [
    { label: "Initial Investment", value: `-R${(systemCost / 1000000).toFixed(2)}M`, color: COLORS.danger },
    { label: "Payback Period", value: `${payback.toFixed(1)} Years`, color: COLORS.warning },
    { label: "25-Year Net Returns", value: `+R${(total25yr / 1000000).toFixed(1)}M`, color: COLORS.primary },
  ];
  
  finMetrics.forEach((metric, i) => {
    const x = margin + i * (cardW + 5);
    
    pdf.setFillColor(metric.color.r, metric.color.g, metric.color.b);
    pdf.roundedRect(x, yPos, cardW, 40, 4, 4, "F");
    
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(255, 255, 255);
    pdf.text(metric.value, x + 8, yPos + 18);
    
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text(metric.label, x + 8, yPos + 32);
  });

  yPos += 55;

  // Yearly cash flow table
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Projected Cash Flow", margin, yPos);
  yPos += 8;

  const yearData = [];
  for (let yr = 1; yr <= 10; yr++) {
    const cumSavings = annualSave * yr;
    const netPosition = cumSavings - systemCost;
    yearData.push([
      `Year ${yr}`,
      `R${Math.round(annualSave / 1000).toLocaleString()}k`,
      `R${Math.round(cumSavings / 1000).toLocaleString()}k`,
      netPosition >= 0 ? `+R${Math.round(netPosition / 1000).toLocaleString()}k` : `-R${Math.round(Math.abs(netPosition) / 1000).toLocaleString()}k`,
    ]);
  }

  autoTable(pdf, {
    startY: yPos,
    head: [["Year", "Annual Savings", "Cumulative Savings", "Net Position"]],
    body: yearData,
    theme: "grid",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 8, halign: "center" },
    columnStyles: { 0: { halign: "left" } },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY || yPos + 80;
}

function renderEnvironmentalImpact(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  const co2 = data.co2AvoidedTons;
  const treesEquiv = Math.round(co2 * 45);
  const lifetime25 = co2 * 25;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(60, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Environmental Benefits", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  // Main impact cards
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Annual Environmental Impact", margin, yPos);
  yPos += 12;

  const halfWidth = (contentWidth - 10) / 2;
  
  // CO2 Card
  pdf.setFillColor(220, 252, 231);
  pdf.roundedRect(margin, yPos, halfWidth, 60, 6, 6, "F");
  
  pdf.setFontSize(36);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(22, 163, 74);
  pdf.text(`${Math.round(co2)}`, margin + 15, yPos + 35);
  
  pdf.setFontSize(14);
  pdf.text("tonnes", margin + 70, yPos + 28);
  pdf.setFontSize(10);
  pdf.text("CO₂/year", margin + 70, yPos + 42);
  
  // Trees Card
  pdf.setFillColor(240, 253, 244);
  pdf.roundedRect(margin + halfWidth + 10, yPos, halfWidth, 60, 6, 6, "F");
  
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(22, 163, 74);
  pdf.text(`${treesEquiv.toLocaleString()}`, margin + halfWidth + 25, yPos + 35);
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text("trees equivalent", margin + halfWidth + 25, yPos + 48);

  yPos += 75;

  // 25-year impact
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("25-Year Lifetime Impact", margin, yPos);
  yPos += 12;

  const impactMetrics = [
    { label: "CO₂ Avoided", value: `${Math.round(lifetime25 / 1000).toLocaleString()}k tonnes` },
    { label: "Trees Equivalent", value: `${Math.round(lifetime25 * 45 / 1000).toLocaleString()}k trees` },
    { label: "Cars Removed", value: `${Math.round(lifetime25 / 4).toLocaleString()} cars/year` },
  ];

  autoTable(pdf, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: impactMetrics.map(m => [m.label, m.value]),
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 10 },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY || yPos + 50;
}

function renderMonthlyYield(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(50, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Generation Profile", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  // Monthly generation data
  const monthlyFactors = [1.1, 1.05, 0.95, 0.85, 0.75, 0.7, 0.72, 0.8, 0.9, 1.0, 1.05, 1.1];
  const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const annualKwh = data.solarCapacityKwp * 1600;
  const avgMonthly = annualKwh / 12;
  const monthlyGen = monthlyFactors.map(f => avgMonthly * f);

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("12-Month Solar Generation Forecast", margin, yPos);
  yPos += 12;

  autoTable(pdf, {
    startY: yPos,
    head: [monthNames],
    body: [[...monthlyGen.map(g => `${Math.round(g / 1000)}k`)]],
    theme: "grid",
    headStyles: { fillColor: [34, 197, 94], textColor: 255, halign: "center" },
    styles: { fontSize: 8, halign: "center" },
    margin: { left: margin, right: margin },
  });

  yPos = (pdf as any).lastAutoTable?.finalY + 15;

  // Summary stats
  const summaryCardW = (contentWidth - 10) / 3;
  const summaryData = [
    { label: "Annual Generation", value: `${Math.round(annualKwh / 1000)} MWh` },
    { label: "Monthly Average", value: `${Math.round(avgMonthly / 1000)} MWh` },
    { label: "Specific Yield", value: "1,600 kWh/kWp" },
  ];

  summaryData.forEach((item, i) => {
    const x = margin + i * (summaryCardW + 5);
    
    pdf.setFillColor(240, 253, 244);
    pdf.roundedRect(x, yPos, summaryCardW, 30, 4, 4, "F");
    
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(34, 197, 94);
    pdf.text(item.value, x + 8, yPos + 14);
    
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100, 100, 100);
    pdf.text(item.label, x + 8, yPos + 24);
  });

  return yPos + 45;
}

function renderEnergyFlow(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  
  const annualGen = data.solarCapacityKwp * 1600;
  const selfConsume = annualGen * 0.65;
  const gridExport = annualGen * 0.35;
  const gridImport = annualGen * 0.15;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(50, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Energy Distribution", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("System Energy Distribution", margin, yPos);
  yPos += 15;

  // Energy flow table
  const flowData = [
    ["Solar Generation", `${Math.round(annualGen / 1000)} MWh/year`, "100%"],
    ["Self-Consumption", `${Math.round(selfConsume / 1000)} MWh/year`, "65%"],
    ["Grid Export", `${Math.round(gridExport / 1000)} MWh/year`, "35%"],
    ["Grid Import", `${Math.round(gridImport / 1000)} MWh/year`, "-"],
  ];

  autoTable(pdf, {
    startY: yPos,
    head: [["Energy Flow", "Annual Volume", "Percentage"]],
    body: flowData,
    theme: "grid",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 10 },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY + 15;
}

function renderSizingComparison(
  pdf: jsPDF,
  startY: number,
  margin: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  const contentWidth = pageWidth - 2 * margin;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(50, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Sizing Analysis", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("System Sizing Alternatives", margin, yPos);
  yPos += 12;

  // Calculate scenarios
  const costPerKwp = 12000;
  const batteryPerKwh = 6000;
  
  const scenarios = [
    { name: "Conservative", factor: 0.7, batFactor: 0.5 },
    { name: "Current Design", factor: 1.0, batFactor: 1.0, isCurrent: true },
    { name: "Aggressive", factor: 1.35, batFactor: 2.0 },
  ].map(s => {
    const solarKwp = Math.round(data.solarCapacityKwp * s.factor);
    const batteryKwh = Math.round(data.batteryCapacityKwh * s.batFactor);
    const systemCost = solarKwp * costPerKwp + batteryKwh * batteryPerKwh;
    const annualSavings = Math.round(data.annualSavings * s.factor);
    const paybackYears = systemCost / annualSavings;
    const roi25yr = ((annualSavings * 25 - systemCost) / systemCost) * 100;
    
    return {
      ...s,
      solarKwp,
      batteryKwh,
      systemCost,
      annualSavings,
      paybackYears,
      roi25yr,
    };
  });

  autoTable(pdf, {
    startY: yPos,
    head: [["Metric", "Conservative", "Current Design", "Aggressive"]],
    body: [
      ["Solar Capacity", `${scenarios[0].solarKwp} kWp`, `${scenarios[1].solarKwp} kWp`, `${scenarios[2].solarKwp} kWp`],
      ["Battery Storage", `${scenarios[0].batteryKwh} kWh`, `${scenarios[1].batteryKwh} kWh`, `${scenarios[2].batteryKwh} kWh`],
      ["System Cost", `R${Math.round(scenarios[0].systemCost / 1000)}k`, `R${Math.round(scenarios[1].systemCost / 1000)}k`, `R${Math.round(scenarios[2].systemCost / 1000)}k`],
      ["Annual Savings", `R${Math.round(scenarios[0].annualSavings / 1000)}k`, `R${Math.round(scenarios[1].annualSavings / 1000)}k`, `R${Math.round(scenarios[2].annualSavings / 1000)}k`],
      ["Payback Period", `${scenarios[0].paybackYears.toFixed(1)} yrs`, `${scenarios[1].paybackYears.toFixed(1)} yrs`, `${scenarios[2].paybackYears.toFixed(1)} yrs`],
      ["25-Year ROI", `${Math.round(scenarios[0].roi25yr)}%`, `${Math.round(scenarios[1].roi25yr)}%`, `${Math.round(scenarios[2].roi25yr)}%`],
    ],
    theme: "grid",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 9, halign: "center" },
    columnStyles: {
      0: { fontStyle: "bold", halign: "left" },
      2: { fillColor: [240, 253, 244] },
    },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY + 15;
}

function renderSensitivityAnalysis(
  pdf: jsPDF,
  startY: number,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(50, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Risk Analysis", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  const systemCost = data.solarCapacityKwp * 12000 + data.batteryCapacityKwh * 6000;
  const basePayback = data.paybackYears;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Sensitivity Analysis - Payback Scenarios", margin, yPos);
  yPos += 15;

  // Tariff escalation impact
  const escRates = [0, 5, 10, 15, 20];
  const escData = escRates.map(rate => {
    if (rate === 0) return [rate + "%", basePayback.toFixed(1) + " yrs"];
    let cumSavings = 0;
    let year = 0;
    let annualSave = data.annualSavings;
    while (cumSavings < systemCost && year < 25) {
      year++;
      cumSavings += annualSave;
      annualSave *= (1 + rate / 100);
    }
    const payback = year + (systemCost - (cumSavings - annualSave)) / annualSave;
    return [rate + "%", payback.toFixed(1) + " yrs"];
  });

  autoTable(pdf, {
    startY: yPos,
    head: [["Tariff Escalation Rate", "Payback Period"]],
    body: escData,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin },
  });

  yPos = (pdf as any).lastAutoTable?.finalY + 15;

  // System cost variation
  const costVars = [-20, -10, 0, 10, 20];
  const costData = costVars.map(pct => {
    const adjustedCost = systemCost * (1 + pct / 100);
    const payback = adjustedCost / data.annualSavings;
    return [pct === 0 ? "Base" : (pct > 0 ? "+" : "") + pct + "%", payback.toFixed(1) + " yrs"];
  });

  autoTable(pdf, {
    startY: yPos,
    head: [["System Cost Variation", "Payback Period"]],
    body: costData,
    theme: "striped",
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY + 15;
}

function renderEngineeringSpecs(
  pdf: jsPDF,
  startY: number,
  margin: number,
  pageWidth: number,
  data: PDFGeneratorConfig["simulationData"],
  narrative?: string
): number {
  let yPos = startY;
  const contentWidth = pageWidth - 2 * margin;
  
  if (narrative) {
    pdf.setFillColor(248, 250, 252);
    const lines = pdf.splitTextToSize(narrative, contentWidth - 16);
    const boxHeight = Math.min(50, 16 + lines.length * 4);
    pdf.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(22, 163, 74);
    pdf.text("Technical Overview", margin + 6, yPos + 10);
    
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(60, 60, 60);
    const maxLines = Math.floor((boxHeight - 14) / 4);
    pdf.text(lines.slice(0, maxLines), margin + 6, yPos + 18);
    
    yPos += boxHeight + 10;
  }

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(15, 23, 42);
  pdf.text("Technical Specifications", margin, yPos);
  yPos += 12;

  const inverterSize = Math.round(data.solarCapacityKwp / (data.dcAcRatio || 1.3));

  autoTable(pdf, {
    startY: yPos,
    head: [["Component", "Specification", "Notes"]],
    body: [
      ["PV Array Size", `${data.solarCapacityKwp} kWp`, "Total DC capacity"],
      ["DC/AC Ratio", `${(data.dcAcRatio || 1.3).toFixed(2)}:1`, "Oversizing factor"],
      ["Inverter Capacity", `${inverterSize} kW`, "Total AC capacity"],
      ["Battery Storage", `${data.batteryCapacityKwh} kWh`, "Usable capacity"],
      ["Expected PR", "80-82%", "Performance ratio"],
      ["Specific Yield", "~1,600 kWh/kWp/yr", "South Africa average"],
      ["System Lifetime", "25 years", "Warranty period"],
    ],
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94], textColor: 255 },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin },
  });

  return (pdf as any).lastAutoTable?.finalY + 15;
}
